const profile = {
  name: 'Ervandra Halim',
  title: 'Technology Lead',
  mission: 'Combining Technology & Creativity For A Greater Impact',
  email: 'hi@ervandra.com',
  phone: '+6287708770800',
  photo: 'https://www.ervandra.com/wp-content/uploads/2020/12/ervan-round.png',
  about:
    "I'm Ervandra Halim, a Technology Enthusiast. Through-out my entire career, i realize that i love the most to conceptualize a website or web applications, write technical specifications and develop it with my team into a high-quality applications that are feasible, scalable, testable and measurable that will also meet with the business requirements.",
  offerIntro:
    'Get my thoughts twice a week in a bite size tech news called the Overcodes, where i cover about latest technologies, programming tips and modern business.',
  intro:
    "I'm a technology lead based in Jakarta, Indonesia specializing in crafting (and occasionally designing) exceptional, highly-effective websites and applications.",
  professionalSkills: [
    'Front-End Development',
    'HTML & CSS (SASS)',
    'React.js - Next.js',
    'Styled Components',
    'Figma / Sketch',
    'GIT / SVN',
    'CI / CD (Deployment)',
    'Responsive Web Design',
    'Business-To-Technical Specifications',
  ],
  personalSkills: [
    'Critical Thinking',
    'Reliable & Professional',
    'Organized & Analytical',
    'Time Management',
    'Fast Learning',
    'Problem Solver',
    'Team Building',
  ],
  website: 'www.ervandra.dev',
  social: [
    'https://linkedin.com/in/ervandra',
    'https://facebook.com/vahnisme',
    'https://github.com/ervandra',
    'https://youtube.com/c/ervandra',
  ],
  socialLinks: [
    {
      id: 'github',
      icon: 'github',
      link: 'https://www.github.com/ervandra',
    },
    {
      id: 'facebook',
      icon: 'facebook',
      link: 'https://www.facebook.com/ervandra.dev',
    },
    {
      id: 'instagram',
      icon: 'instagram',
      link: 'https://www.instagram.com/ervandra.dev',
    },
    {
      id: 'youtube',
      icon: 'youtube',
      link: 'https://www.youtube.com/c/ervandra',
    },
    {
      id: 'linkedin',
      icon: 'linkedin',
      link: 'https://www.linkedin.com/in/ervandra',
    },
  ],
  experiences: [
    {
      company: 'R/GA',
      logoCompany: 'https://via.placeholder.com/12/e51837?text=+',
      promotion: [
        {
          title: 'Technology Lead',
          year: 'May 2022 - Present',
          summary: [
            'Connecting people across globe through technical assesment for potential project and collaboration',
            'Oversee & Manage APAC (Indonesia Office) Technology Team to ensure working experience, growing factor, and successful deliveries.',
            'Work with R/GA teams across multiple offices, collaborating with multiple disciplines',
            'Evaluate and recommend technology solutions that best fit project requirements',
            'Collaborate with experience and visual design, strategy to build and deliver successful digital experiences with technical solutions',
            'Assist teams on technical feasibility, risk and effort estimation',
            'Help with technical assessment and prototyping to de-risk and prove out concepts',
            'Write clean, readable, modern, secure, robust and well performing code according to world-class standards',
            'Lead by example and mentoring junior members on best-practices on daily basis',
            'Manage tasks and workloads responsibly to ensure successful development and project deliverables',
          ],
        },
        {
          title: 'Senior Software Engineer, Web Platforms',
          year: 'May 2021 - April 2022',
          summary: [
            'Work with R/GA teams across multiple offices, collaborating with multiple disciplines',
            'Evaluate and recommend technology solutions that best fit project requirements',
            'Collaborate with experience and visual design, strategy to build and deliver successful digital experiences with technical solutions',
            'Assist teams on technical feasibility, risk and effort estimation',
            'Help with technical assessment and prototyping to de-risk and prove out concepts',
            'Write clean, readable, modern, secure, robust and well performing code according to world-class standards',
            'Lead by example and mentor junior members on best-practices on daily basis',
            'Manage tasks and workloads responsibly to ensure successful development and project deliverables',
          ],
        },
      ],
    },
    {
      company: 'CIAYO',
      logoCompany:
        'https://media-exp1.licdn.com/dms/image/C560BAQGey9YiNk4yOw/company-logo_100_100/0/1519872267902?e=1627516800&v=beta&t=jH7xtdbxvkk_qThbSiOn2x-jjfgreOZg_eO_49wsrVw',
      promotion: [
        {
          title: 'Lead Frontend Developer',
          year: 'Dec 2016 - Jul 2020',
          summary: [
            'Write technical specifications, help my team to meet business requirements',
            'Create blueprint project, and scaling the apps',
            'Code review, upgrading version and optimizing features',
            'Recoding web apps to catch the latest technology updates',
            'Transform UI into interactive components and smooth client view',
            'Planning deployments, manage release and implement CI/CD',
            'Hands-on to coding and styling main project and other micro-site projects',
          ],
        },
        {
          title: 'Senior Frontend Developer',
          year: 'Jun 2015 - Dec 2016',
          summary: [
            'Joined as Co-Founder and contribute useful insights regarding web technologies to PT. Dragon Capital Centre',
            'Lead development of CIAYO (Virtual Social Media) using AngularJS',
            'Lead development of CIAYO Comics with team using React.js',
            'Successfully improving and recoding the web apps using Nuxt.js (and later Next.js - React.js',
          ],
        },
      ],
    },
    {
      company: 'Cakra Studio',
      logoCompany:
        'https://media-exp1.licdn.com/dms/image/C560BAQEox87eYfzT4w/company-logo_100_100/0/1519880025972?e=1627516800&v=beta&t=mjeIOB44eAeZ--4ER-MYYw83DzJjH8EmC2RI0Wcg_aQ',
      promotion: [
        {
          title: 'Senior Web Analyst',
          year: 'Jul 2012 - Jun 2015',
          summary: [
            'Manage discussion with potential clients and create technical estimation',
            'Leading and managing Web Development Team to ensure deliverables',
            "Create report and documentation for client's projects",
            "Improve company's website together with team to improve visibility and experiences.",
          ],
        },
        {
          title: 'Senior Web Developer',
          year: 'Jul 2012 - Jun 2015',
          summary: [
            'Create standardize Web Services for the company',
            "Create boilerplate Wordpress Template to be used for our client's projects",
            'Hands-on create WordPress website for clients',
            'Provide design suggestion and actionables for better web experiences',
          ],
        },
      ],
    },
  ],
  education: [
    {
      title: 'Bachelor of Computer Science (Interactive Multimedia)',
      school: 'Bina Nusantara University',
      year: '2008 - 2012',
    },
  ],
  color: 'ae2b26',
  cover: 'https://i.imgur.com/i4NZURh.jpg',
  recentSkills: [
    'Next.js + TailwindCSS',
    'TypeScript',
    'Python',
    'Microsoft Azure',
    'Contentful',
    'Storybook',
    'Uniform',
    'GraphCMS',
  ],
  allSkills: [
    'React.js',
    'TailwindCSS',
    'Styled Components',
    'CSS Modules',
    'Atomic Design',
    'Serverless',
    'Google Cloud',
    'Firebase',
    'Firestore',
    'Angular',
    'Vue.js | Nuxt.js',
    'Material UI',
    'React Native',
    'Flutter',
    'Miro',
    'Figma',
    'Sketch',
    'Zeplin',
    'Adobe XD',
    'Go Retro',
    'Jira',
    'Asana',
    'Trello',
    'Slack',
    'Netlify',
    'Vercel',
    'Gatsby',
    'AWS',
    'AWS Lambda',
    'AWS SES',
    'AWS EC2',
    'JAMStack',
    'HeadlessCMS',
    'Uniform',
    'Contentful',
    'GraphCMS',
    'Sanity',
    'CDN',
    'CI/CD',
    'Cloudflare',
    'WordPress',
    'Woocommerce',
    'Payment Gateway',
    'Custom Interation',
    'Custom Software Development',
    'Technical Feasibility',
    'Technical Documentation',
    'Technical Design',
    'Technical Architecture',
    'Team building',
    'Team management',
    'Project management',
    'Protopie',
    'MVP',
    'Balsamiq',
    'Whimsical',
  ],
};

export default profile;
